spring:
  application:
    name: jwt-code-challenge
  output.ansi.enabled: ALWAYS

logging:
  level:
    com.matheusrangel.jwtcodechallenge: ${LOG_LEVEL:DEBUG}
    org.springframework.web.filter.CommonsRequestLoggingFilter: ${LOG_LEVEL:DEBUG}

jwt:
  signed: ${JWT_SIGNED:false}
  signing-key: ${JWT_SIGNING_KEY:24C826EFA558F4AEBAA36DBC8C2559276B11D64C9CDCC72C98BB3EE4C8}
  valid-roles: ${JWT_VALID_ROLES:Admin,Member,External}