spring:
  application:
    name: jwt-code-challenge
  output.ansi.enabled: ALWAYS

logging:
  level:
    com.matheusrangel.jwtcodechallenge: DEBUG

jwt:
  signed: false
  signing-key: 24C826EFA558F4AEBAA36DBC8C2559276B11D64C9CDCC72C98BB3EE4C8
  valid-roles: ["Admin", "Member", "External"]